import{S as d,N as m,K as u,i as h}from"./assets/vendor-c4700f22.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&c(n)}).observe(document,{childList:!0,subtree:!0});function a(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(t){if(t.ep)return;t.ep=!0;const o=a(t);fetch(t.href,o)}})();const f=new d(".reviews-swiper",{direction:"horizontal",loop:!1,navigation:{nextEl:".button-next",prevEl:".button-prev"},keyboard:{enabled:!0,onlyInViewport:!0},modules:[m,u],breakpoints:{320:{slidesPerView:1,spaceBetween:20},480:{slidesPerView:2,spaceBetween:30},640:{slidesPerView:2,spaceBetween:40}}});function l(e){h.error({title:"Error",message:e})}function p(e){return console.log(e),`<li class="swiper-slide review-list-item">
          <p class="review-section-text">${e.author}</p>
          <div class="review-avatar-text">
        <img
         srcset="${e.avatar_url}"
         class="review-section-img"
         src="${e.avatar_url}"
         alt="Avatar"/>
            <h3 class="review-section-title">${e.review}</h3>
          </div>
        </li>`}function g(e){return e.map(p).join("")}function w(e){const r=document.getElementById("reviews-list"),a=g(e);r.innerHTML=a,f.update()}async function y(){try{const e=await fetch("https://portfolio-js.b.goit.study/api/reviews");if(!e.ok)throw new Error("Failed to fetch reviews");const r=await e.json();console.log(r),r&&r.length>0?w(r):(l("No reviews found"),document.getElementById("reviews-list").innerHTML="<p>Not found</p>")}catch{l("An error occurred while fetching reviews"),document.getElementById("reviews-list").innerHTML="<p>Not found</p>"}}document.addEventListener("DOMContentLoaded",y);const i={colorThema:""},s=document.querySelector("body"),v=JSON.parse(localStorage.getItem("typeThema"));v||(console.log("localstorage is clear"),i.colorThema="light",s.classList.add("lightthema"),localStorage.setItem("typeThema",JSON.stringify(i)));const T=document.querySelector(".switchthema");T.addEventListener("click",L);function L(e){const r=JSON.parse(localStorage.getItem("typeThema"));if(console.log("localStore Thema:",r.colorThema),r.colorThema=="dark"){s.classList.contains("darkthema")&&s.classList.remove("darkthema"),i.colorThema="light",localStorage.setItem("typeThema",JSON.stringify(i)),s.classList.add("lightthema");return}else{s.classList.contains("lightthema")&&s.classList.remove("lightthema"),i.colorThema="dark",localStorage.setItem("typeThema",JSON.stringify(i)),s.classList.add("darkthema");return}}
//# sourceMappingURL=commonHelpers.js.map
